### ISSUE TITLE
Deprecation warning for "slds-scope" for non LWC html files

### ISSUE THREAD

**Issue by mjyocca** [forcedotcom/salesforcedx-vscode-slds#40]
### Summary

Getting, `Deprecated, or invalid, utility class: "slds-scope"` w/ in a nested Angular project directory *.html file. Since our target is visualforce we need certain elements w/ this class on it. To my knowledge this class is not deprecated. Is there currently a way to tell SLDS Validator to ignore files/directories completely or to individually ignore certain rules and or lines in files? 

The linter is very useful but might need to disable for now. 

### Steps To Reproduce:

1.  Create a SFDX project
2. Create a sub directory and initialize a angular project or create a test.html file w/ a element containing a class of "slds-scope"

<img width="1178" alt="Screen Shot 2020-08-18 at 11 25 51 AM" src="https://user-images.githubusercontent.com/19916665/90551035-9fe80f00-e145-11ea-8b0a-2ebaf90c1118.png">

**VS Code Version**: 1.48.0

**SFDX CLI Version**: 7.70.1

**OS and version**: macOS 10.15.6

**Comment by ambreeen** [comment]
Hi @mjyocca. There are some SLDS classes in Visualforce that are not a part of standard SLDS, which is why you see the error. Unfortunately there is not a way to ignore files and directories at the moment. We will look into adding Visualforce support for the SLDS Validator and having a way to ignore lines/files/directories, etc. Thanks.

**Comment by mjyocca** [comment]
@ambreeen Ahh good to know. Having a way to ignore individual lines would solve our issue. Will watch #42 for updates. Thanks!
